spring.application.name=api-gateway
server.port = 9000

# Actuator & Prometheus (scraped by Prometheus in docker-compose)
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when_authorized
management.metrics.tags.application=${spring.application.name}

#Resilinece4j Properties
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.configs.default.slidingWindowSize=8
resilience4j.circuitbreaker.configs.default.failureRateThreshold=20
resilience4j.circuitbreaker.configs.default.minimum-number-of-calls=4
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=5s
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true

#keycloak
keycloak.auth.jwk-set-uri=http://localhost:8091/realms/homewatt/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8091/realms/homewatt

# URLs excluded from authentication
#Security
security.excluded.urls= /actuator/**, /swagger-ui.html, /swagger-ui/**, /docs/**, /v3/api-docs/**, /swagger-resources/**, /api-docs/**

#OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.urls[0].name=User Service
springdoc.swagger-ui.urls[0].url=/docs/user-service/v3/api-docs
springdoc.swagger-ui.urls[1].name=Device Service
springdoc.swagger-ui.urls[1].url=/docs/device-service/v3/api-docs
springdoc.swagger-ui.urls[2].name=Ingestion Service
springdoc.swagger-ui.urls[2].url=/docs/ingestion-service/v3/api-docs
springdoc.swagger-ui.urls[3].name=Insight Service
springdoc.swagger-ui.urls[3].url=/docs/insight-service/v3/api-docs

